version: '3.2'

services:
  postgres:
    image: postgres
    ports: [5432:5432]
    environment:
      POSTGRES_PASSWORD: password
    volumes: [postgres-data:/var/lib/postgresql/data]

  hasura:
    image: hasura/graphql-engine:v1.3.0.cli-migrations-v2
    depends_on: [postgres]
    ports: [8080:8080]
    restart: unless-stopped
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:password@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'false'
      HASURA_GRAPHQL_ENABLE_TELEMETRY: 'false'
      HASURA_GRAPHQL_MIGRATIONS_DIR: /hasura/migrations/
      HASURA_GRAPHQL_METADATA_DIR: /hasura/metadata/
    volumes:
      - &hasura_volume
        type: bind
        source: .
        target: /hasura/
        consistency: delegated
    working_dir: &working_dir /hasura/

  console:
    build: .
    depends_on: [hasura]
    ports: [9693:9693, 9695:9695]
    restart: unless-stopped
    environment:
      HASURA_GRAPHQL_ENABLE_TELEMETRY: 'false'
    volumes: [*hasura_volume]
    working_dir: *working_dir

volumes:
  postgres-data: {}
