version: '3.8'

services:
  postgres:
    image: postgres@sha256:57e21ed66832b61c13192684b140f2dc23fdc9b36b5c9c49e11cecfc23a59a45
    ports: [5432:5432]
    environment:
      POSTGRES_PASSWORD: password
    volumes: [postgres-data:/var/lib/postgresql/data]

  hasura:
    build:
      context: .
      target: server
    depends_on: [postgres]
    ports: [8080:8080]
    restart: unless-stopped
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:password@postgres:5432/postgres

  console:
    build:
      context: .
      target: console
    depends_on: [hasura]
    ports: [9693:9693, 9695:9695]
    restart: unless-stopped
    volumes:
      - type: bind
        source: .
        target: /hasura/
        consistency: delegated
    working_dir: /hasura/

volumes:
  postgres-data: {}
