version: '3.8'

services:
  postgres:
    image: postgres@sha256:b6a3459825427f08ab886545c64d4e5754aa425c5eea678d5359f06a9bf7faab
    ports: [5432:5432]
    environment:
      POSTGRES_PASSWORD: password
    volumes: [postgres-data:/var/lib/postgresql/data]

  hasura:
    build:
      context: .
      target: server
    depends_on: [postgres]
    ports: [8080:8080]
    restart: unless-stopped
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:password@postgres:5432/postgres

  console:
    build:
      context: .
      target: console
    depends_on: [hasura]
    ports: [9693:9693, 9695:9695]
    restart: unless-stopped
    volumes:
      - type: bind
        source: .
        target: /hasura/
        consistency: delegated
    working_dir: /hasura/

volumes:
  postgres-data: {}
