name: GraphQL schemas generation

on: [push, pull_request]

jobs:
  codegen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile
      - run: yarn run dev:ci
      - run: yarn run generate
      - uses: actions/upload-artifact@v2
        with:
          name: schemas
          path: |
            schema.json
